name: KookSRV
version: '${project.version}'
main: com.ghostchu.plugins.kooksrv.KookSRV
api-version: '1.19'
libraries:
  - org.apache.commons:commons-compress:1.24.0
  - org.apache.commons:commons-lang3:3.13.0
  - org.apache.commons:commons-text:1.10.0
  - com.rollbar:rollbar-java:1.9.0
  - commons-codec:commons-codec:1.15
  - commons-io:commons-io:2.13.0
  - cc.carm.lib:easysql-hikaricp:0.4.7
  - com.h2database:h2:2.1.214
  - com.ghostchu:simplereloadlib:1.1.2
  - com.konghq:unirest-java:3.14.5
  - one.util:streamex:0.8.2
  - commons-lang:commons-lang:2.6
  - net.sourceforge.csvjdbc:csvjdbc:1.0.40
  - org.dom4j:dom4j:2.1.4
  - org.slf4j:slf4j-jdk14:2.0.7
  - com.vdurmont:semver4j:3.1.0
  - com.google.code.gson:gson:2.10.1
  - net.kyori:adventure-api:4.14.0
  - net.kyori:adventure-key:4.14.0
  - net.kyori:adventure-nbt:4.14.0
  - net.kyori:adventure-platform-api:4.3.0
  - net.kyori:adventure-platform-bukkit:4.3.0
  - net.kyori:adventure-platform-facet:4.3.0
  - net.kyori:adventure-platform-viaversion:4.3.0
  - net.kyori:adventure-serializer-configurate4:4.14.0
  - net.kyori:adventure-text-logger-slf4j:4.14.0
  - net.kyori:adventure-text-minimessage:4.14.0
  - net.kyori:adventure-text-serializer-ansi:4.14.0
  - net.kyori:adventure-text-serializer-bungeecord:4.3.0
  - net.kyori:adventure-text-serializer-gson-legacy-impl:4.14.0
  - net.kyori:adventure-text-serializer-json:4.14.0
  - net.kyori:adventure-text-serializer-json-legacy-impl:4.14.0
  - net.kyori:adventure-text-serializer-legacy:4.14.0
  - net.kyori:adventure-text-serializer-plain:4.14.0
  - net.kyori:examination-api:1.3.0
  - net.kyori:examination-string:1.3.0
commands:
  kookchat:
    aliases: [kook]
    description: Main command for KOOK-Chat
